---
- hosts: all
  become: yes
  roles:
    - monolithprojects.github_actions_runner

  vars:
    runner_user: "{{ lookup('env', 'USER') }}"
    runner_dir: /home/kk573/work/github/runners/slotegrator-task3
    runner_version: "2.311.0"
    runner_state: "started"
    reinstall_runner: false
    hide_sensitive_logs: yes
    runner_labels: [home]
    runner_group: ""
    runner_download_repository: "actions/runner"
    runner_extra_config_args: ""
    runner_name: "{{ ansible_facts.hostname }}"
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    github_repo: "{{ lookup('env', 'GITHUB_REPO') }}"
    access_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
