name: Build main app image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'app.py'
      - 'headers.html'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set base image docker tag
        run: echo "BASE_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Cache pip files
        id: cache-pip-files
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: python-pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-pip-${{ runner.os }}-

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-app:${{ env.BASE_IMAGE_TAG }}
            ghcr.io/${{ github.repository }}-app:latest

      - name: Save BASE_IMAGE_TAG to cache
        id: save-cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-image-tag-${{ env.BASE_IMAGE_TAG }}
          restore-keys: |
            ${{ runner.os }}-image-tag-
