name: Build app image

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore BASE_IMAGE_TAG from cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: base-image-tag
          restore-keys: base-image-tag

      - name: Check if cache was restored
        run: |
          if [ -z "${{ steps.restore-cache.outputs.path }}" ]; then
            echo "Cache was not restored. Stopping pipeline with an error."
            exit 1
          fi

      - name: Set APP_IMAGE_TAG
        run: echo "APP_IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-app:${{ env.APP_IMAGE_TAG }}
            ghcr.io/${{ github.repository }}-app:latest
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}

      - name: Save BASE_IMAGE_TAG to cache
        id: save-cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-base-image-tag-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-base-image-tag-
