name: Build main app image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'app.py'
      - 'headers.html'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Short SHA
        run: echo "${{ env.SHORT_SHA }}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-app:"${{ env.SHORT_SHA }}"
            ghcr.io/${{ github.repository }}-app:latest

